version: 1
disable_existing_loggers: true
# Configuring the default (root) logger is highly recommended
root:
  level: INFO
  handlers: [console]
loggers:
  # Logging from application
  {{cookiecutter.repo_name}}:
    level: INFO
    handlers: [console]
    qualname: {{cookiecutter.repo_name}}
    propagate: false
  drtools.utils.task:
    level: INFO
    handlers: [container]
    qualname: drtools.utils.task
    propagate: false
handlers:
  console:
    class: logging.StreamHandler
    stream: ext://sys.stdout
    formatter: simple
    level: INFO
formatters:
  simple:
    class: logging.Formatter
    format: '%(name)s %(asctime)s %(levelname)s %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  container:
    class: logging.Formatter
    format: 'CONTAINER| %(message)s'