version: '2.1'
services:
    dask-worker:
      volumes:
        - ${MODULES_PATH-..}/sparsity:/home/drtools/sparsity
        - ${MODULES_PATH-..}/drtools_base:/home/drtools/drtools
        - ${MODULES_PATH-..}/{{ cookiecutter.repo_name }}:/home/drtools/{{ cookiecutter.repo_name }}

      environment:
        - PYTHONPATH=/home/drtools/{{ cookiecutter.repo_name }}/:/home/drtools/drtools/:/home/drtools/sparsity/
        - DRTOOLS_SETTINGS_MODULE={{ cookiecutter.repo_name }}.settings.dev

    controller:
      volumes:
        - ${MODULES_PATH-..}/sparsity:/home/drtools/sparsity
        - ${MODULES_PATH-..}/drtools_base:/home/drtools/drtools
        - ${MODULES_PATH-..}/{{ cookiecutter.repo_name }}:/home/drtools/{{ cookiecutter.repo_name }}

      environment:
        - PYTHONPATH=/home/drtools/{{ cookiecutter.repo_name }}/:/home/drtools/drtools/:/home/drtools/sparsity/
        - DRTOOLS_SETTINGS_MODULE={{ cookiecutter.repo_name }}.settings.dev
        - MODULES_PATH
