version: '2'
services:
    luigid:
      image: axiom/docker-luigi
      container_name: luigid
      ports:
          - "8082:8082"

      command: luigid
      networks:
          - dev

    dask-scheduler:
      image: drtools/drtools:latest
      command: dask-scheduler
      container_name: dask-scheduler
      networks:
        - dev
      depends_on:
          - dask-worker
      ports:
        - "8787:8787"
        - "8788:8788"


    dask-worker:
      image: drtools/drtools:latest
      volumes:
        - "./root_dir:/home/drtools/{{ cookiecutter.repo_name }}/root_dir"
      ports:
        - "8789:8789"
      networks:
        - dev
      command: >
                 dask-worker dask-scheduler:8786
                 --nprocs {{cookiecutter.dask_nprocs}}
                 --memory-limit {{cookiecutter.dask_mem_limit}}
networks:
  dev:
    external: false