version: '2.1'
services:
    luigid:
      image: axiom/docker-luigi
      container_name: luigid
      ports:
        - "8082:8082"

      command: luigid
      networks:
        - dev

    dask-scheduler:
      image: drtools/drtools:latest
      command: dask-scheduler
      container_name: dask-scheduler
      networks:
        - dev
      ports:
        - "8787:8787"
        - "8788:8788"


    dask-worker:
      image: drtools/{{ cookiecutter.repo_name }}:latest
      depends_on:
        - dask-scheduler
      volumes:
        - ./root_dir:/home/drtools/{{ cookiecutter.repo_name }}/root_dir
      ports:
        - "8789:8789"
      networks:
        - dev
      command: >
                 dask-worker dask-scheduler:8786
                 --nprocs {{cookiecutter.dask_nprocs}}
                 --memory-limit {{cookiecutter.dask_mem_limit}}

    controller:
      image: drtools/{{ cookiecutter.repo_name }}:latest
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock
      networks:
        - dev

# Uncomment this section and set SMTP_PASS var to enable luigi notifications
#    smtp-relay:
#      image: juanluisbaptiste/postfix:latest
#      environment:
#        - SMTP_SERVER=mail.privateemail.com
#        - SMTP_USERNAME=luigi@datarevenue.de
#        - SMTP_PASSWORD=$SMTP_PASS
#        - SERVER_HOSTNAME=datarevenue.de

networks:
  dev:
    external: false