#!/usr/bin/env bash
set -e
# creates wheels on current commit
cd $HOME/bin/deploy/
export VERSION=${1:-`git rev-parse HEAD`}
python -c \
"print(' {wrap}\n\n{message:^100}\n\n {wrap}'
        .format(wrap='='*100,
                message='Building {{cookiecutter.repo_name}} Release ${VERSION}'))"
printf '\n\n'

python -c \
"print(' {wrap}\n{message:^60}\n {wrap}'.format(wrap='.'*60, message='Building Wheelhouse'))"

docker run \
    -i \
    -v $HOME/bin/deploy/wheelhouse:/home/ubuntu/wheelhouse \
    -w /home/ubuntu \
    --entrypoint /bin/bash \
    -e "VERSION=${VERSION}" \
         -c "git clone git@github.com:datarevenue-berlin/{{cookiecutter.repo_name}}.git &&
             cd {{cookiecutter.repo_name}} &&
             git checkout ${VERSION} &&
             pip wheel . --wheel-dir ../wheelhouse --process-dependency-link &&
             bash deploy/xgboost_wheel.sh /home/ubuntu/wheelhouse"

python -c \
"print(' {wrap}\n{message:^60}\n {wrap}'.format(wrap=' '*60, message='WHEELHOUSE: OK'))"

python -c \
"print(' {wrap}\n\n{message:^100}\n\n {wrap}'.format(wrap='.'*100, message='Building drtools/{{cookiecutter.repo_name}}-worker:${VERSION}'))"

# build main container
docker build -t drtools/{{cookiecutter.repo_name}}-worker:$VERSION -f main.dockerfile .

python -c \
"print(' {wrap}\n{message:^60}\n {wrap}'.format(wrap=' '*60, message='BUILD: SUCCESS'))"

echo "New image available as: drtools/{{cookiecutter.repo_name}}-worker:${VERSION}"
