version: '2'
services:
    worker:
      image: drtools/{{cookiecutter.repo_name}}-worker:${VERSION}
      build:
        context: .
        dockerfile: main.dockerfile

      restart: always
      depends_on:
          - luigid
          - dask-scheduler

      volumes:
        - /srv/is24_user_scoring/data:/srv/is24_user_scoring/data
        - /srv/is24_user_scoring/tmp:/tmp

      environment:
          - DRTOOLS_SETTINGS_MODULE=$PROD_SETTINGS
          - DRTOOLS_DASK_SCHEDULER=dask-scheduler:8786

      command: luigi --module {{cookiecutter.repo_name}}.task LivePredict

    dask-scheduler:
      image: drtools/{{cookiecutter.repo_name}}-worker:${VERSION}
      build: {}
      restart: always
      container_name: ''

    dask-worker:
      image: drtools/{{cookiecutter.repo_name}}-worker:${VERSION}
      build: {}
      container_name: ''

      restart: always
      volumes:
          - /srv/{{cookiecutter.repo_name}}/data:/srv/{{cookiecutter.repo_name}}/data
          - /srv/{{cookiecutter.repo_name}}/tmp:/tmp

      environment:
          - PATH=/home/ubuntu/.local/bin:$PATH
          - DRTOOLS_SETTINGS_MODULE=$PROD_SETTINGS
          - LC_ALL=C.UTF-8
          - LANG=C.UTF8
          - LOCAL_GROUP_ID
          - LOCAL_USER_ID
          - LOCAL_USER

      command: "dask-worker dask-scheduler:8786  --nprocs {{cookiecutter.nprocs}} --memory-limit {{cookiecutter.mem_limit}}"

    luigid:
      image: drtools/{{cookiecutter.repo_name}}-worker:${VERSION}
      container_name: ''
