version: '2'
services:
    worker:
      depends_on:
          - luigid
          - dask-scheduler

      command: /bin/bash

      volumes:
          - /srv/{{cookiecutter.repo_name}}/data:/srv/{{cookiecutter.repo_name}}/data
          - $HOME:/home/$USER
          - $HOME:/home/ubuntu
          - /srv/{{cookiecutter.repo_name}}/tmp:/tmp

      environment:
          - PATH=$HOME/.local/bin:$PATH
          - PYTHONPATH=$HOME/bin/
          - DRTOOLS_SETTINGS_MODULE={{cookiecutter.repo_name}}.settings.dev
          - LOCAL_GROUP_ID
          - LOCAL_USER_ID
          - LOCAL_USER=$USER

      entrypoint: entrypoint.sh