version: '2'
services:
    worker:
        image: drtools/{{cookiecutter.repo_name}}-worker:dev
        build:
          context: .
          dockerfile: dev.dockerfile

    luigid:
        image: drtools/{{cookiecutter.repo_name}}-worker:dev
        container_name: luigid
        build:
          context: .
          dockerfile: dev.dockerfile
        ports:
            - "8082:8082"

        command: luigid

    dask-scheduler:
      image: drtools/{{cookiecutter.repo_name}}-worker:dev
      build:
        context: .
        dockerfile: dev.dockerfile

      command: dask-scheduler
      container_name: dask-scheduler

      depends_on:
          - dask-worker

      environment:
          - PATH=/home/ubuntu/.local/bin:$PATH
          - LC_ALL=C.UTF-8
          - LANG=C.UTF8
          - LOCAL_GROUP_ID
          - LOCAL_USER_ID
          - LOCAL_USER

      ports:
        - "8787:8787"
        - "8788:8788"


    dask-worker:
      image: drtools/{{cookiecutter.repo_name}}-worker:dev
      build:
        context: .
        dockerfile: dev.dockerfile

      volumes:
          - /srv/{{cookiecutter.repo_name}}/data:/srv/{{cookiecutter.repo_name}}/data
          - $HOME:/home/ubuntu
          - /srv/{{cookiecutter.repo_name}}/tmp:/tmp

      environment:
          - PATH=/home/ubuntu/.local/bin:$PATH
          - PYTHONPATH=/home/ubuntu/bin/
          - DRTOOLS_SETTINGS_MODULE={{cookiecutter.repo_name}}.settings.dev
          - LC_ALL=C.UTF-8
          - LANG=C.UTF8
          - LOCAL_GROUP_ID
          - LOCAL_USER_ID
          - LOCAL_USER

      ports:
        - "8789:8789"

      command: "dask-worker dask-scheduler:8786  --nprocs {{cookiecutter.nprocs}} --memory-limit {{cookiecutter.mem_limit}}"